### ISSUE TITLE
javascript 데이터 샘플 파일 필요

### ISSUE THREAD

**Issue by honux77** [KimDahye/NEXTStudentNetwork#21]
데이터를 자바스크립트로 분리한 간단한 마크업 예제를 덧글로 달아주세요.

**Comment by kjhwee91** [comment]
마크업 예제입니다
data-test 브랜치에..아주 간단하게 ^.^ㅠ....작업해뒀습니다!

https://github.com/KimDahye/NEXTStudentNetwork/blob/data-test/webapp/views/personal_profile.html
https://github.com/KimDahye/NEXTStudentNetwork/blob/data-test/webapp/views/main.html

각 페이지 가장 하단에 데이터를 선언해뒀구요 내부적으로는 아래와 같은 순서(?)로 진행되고 있습니다
1. 배열이나 json 형식으로 데이터가 선언
2. 페이지 마다 있는 컨트롤러에 데이터를 넘겨주기
3. 컨트롤러가 초기화 되면서 돔 내부에 데이터 입력하기

감사합니당 ^.6

**Comment by kjhwee91** [comment]
헐 깃허브는 바로 렌더링이 안되네요..흑흑 로컬에서 webapp/views/main.html , personal_profile.html 파일 확인 부탁드려요 ㅠㅠ

**Comment by honux77** [comment]
땡큐, 수고했어
