### ISSUE TITLE
README.md 갱신

### ISSUE THREAD

**Issue by jwvg0425** [KimDahye/NEXTStudentNetwork#24]
지금 상황에서 우선 순위가 높은 이슈는 아닐 듯 싶지만.. README 내용이 예전 프로젝트때의 내용 그대로인 것 같은데 현재 프로젝트 상황을 잘 나타낼 수 있게 한 번 갱신해주는게 좋지 않을까요? ㅎㅎ 프로젝트 진행 내용이나 방향같은게 궁금한데 현재 정해진 내용이 README에 어느정도 정리되어 있으면 도움 주고 싶은 사람들도 자신이 어떤 부분을 도울 수 있는지 명확하게 알 수 있어 좋을 것 같습니당..

**Comment by skatpgusskat** [comment]
저도 비슷한 것을 느꼈습니다. 나중에서야 할게 된 것이 위키 들어가야 좀 알것같더라고요. README.md를 정리하지 못하더라도 최소한 README.md 맨 위에 "개발 도움 주실 분들은 위키 참조하라"는 메시지를 적어주셨으면 좋겠습니다.

**Comment by honux77** [comment]
나도 공감
@KimDahye  이것 보고 정리 좀 해 주세요.

**Comment by KimDahye** [comment]
확인요! :)
