### ISSUE TITLE
마일스톤에 해당하는 개발 내용들을 Issue로 관리해주시면 안될까요?

### ISSUE THREAD

**Issue by skatpgusskat** [KimDahye/NEXTStudentNetwork#26]
저는 그다지 정식적인 팀원이나 카톡같은 지속적인 커뮤니케이션 없이 이슈 단위로 떨어져나오는 과제들을 해결하고 싶습니다.

그래서 혹시 마일스톤 내용이 정리가 된다면 개발이 필요한 내용들을 이슈 단위로 나누어 올려주실 수 있으신가요?

**Comment by honux77** [comment]
이슈 등록 예정인데  아직 등록이 안 되었네요. 각 이슈들 등록되면 해결해서 pull 리퀘 날리세요.

**Comment by KimDahye** [comment]
@skatpgusskat  github으로 적극적으로 참여해줘서 감사~!

**Comment by honux77** [comment]
이 이슈는 닫을게요. @skatpgusskat  필요하다고 생각하면 다시 열어 주세요.
