### ISSUE TITLE
1. 테스트데이터 만들기 

### ISSUE THREAD

**Issue by cpfl300** [KimDahye/NEXTStudentNetwork#32]
승인된 회원목록, 미승인 회원목록이 있어야 함 - 현재 사용하고 있는 mongoDB 참고

**Comment by honux77** [comment]
1. admin 페이지를 빠르게 먼저 만들거나
2. 아니면 현재 유저 정보에서 랜덤하게 confirm 을 true로 만드는 스크립트를 만들어야 겠네요.

2번이 쉽겠다.

**Comment by honux77** [comment]
script 디렉토리에 데이터 생성 스크립트 만들었어요. 풀리퀘 확인!
