### ISSUE TITLE
2. 사용자리스트 가져오는 API만들기/ 화면에 표시

### ISSUE THREAD

**Issue by cpfl300** [KimDahye/NEXTStudentNetwork#33]
[API] 
/admin/list?approval=true
admin/list?approval=false
mongoDB에서 해당 리스트 가져와서 화면에 텍스트 뿌려주기 (활성, 비활성 버튼도 포함)

**Comment by KimDahye** [comment]
(webapp/src/model/user.js에 정의 되어 있는) user 스키마를 보니 위의 approval이 confirm으로 대체된 거 같습니다. 용어는 confirm으로 통일하는 게 좋겠네요!

**Comment by honux77** [comment]
내 실수로 그만 이름이 바뀌었네요. 죄송합니다. 
/admin/list?confirm=true
admin/list?confirm=false

**Comment by honux77** [comment]
비 어드민용 (메인페이지요) API도 만들었습니다.
GET /users 로 승인된 사용자의 목록을 볼 수 있어요.
