### ISSUE TITLE
3. 활성/ 비활성 상태를 변경하는 API 만들기

### ISSUE THREAD

**Issue by cpfl300** [KimDahye/NEXTStudentNetwork#34]
[API]
/changeStatus?status=true
/changeStatus?status=false
버튼 클릭 시 db의 값을 바꾼다.

**Comment by honux77** [comment]
이건 admin api니까 input 값으로 user의 email이 필요한 거지?

**Comment by KimDahye** [comment]
네 체크박스 형태로 하기로 했으니, user email의 리스트가 넘어올 거 같네요~

**Comment by honux77** [comment]
일단 한명의 상태를 바꾸는 API로 만들었는데, status는 없고 changeStatus?email=xxx 하면 xxx의 상태를 바꾸도록 코드를 짰어.

**Comment by honux77** [comment]
완료.
