### ISSUE TITLE
GET /profile 만들기 

### ISSUE THREAD

**Issue by KimDahye** [KimDahye/NEXTStudentNetwork#38]
json으로 내려주는 api가 아니라 html 페이지 내려주는데 데이터 밑에 몰아서

**Comment by honux77** [comment]
https://github.com/KimDahye/NEXTStudentNetwork/blob/data-test/webapp/views/personal_profile.html
참고하면 된대

**Comment by KimDahye** [comment]
주희의 personal_profile.html 참고하여, profile.ejs 파일 만들고 이슈 닫겠다.
