### ISSUE TITLE
api 문서 만들기

### ISSUE THREAD

**Issue by KimDahye** [KimDahye/NEXTStudentNetwork#41]
docs/ 폴더 아래에 서비스별 api 문서를 정리해두자.

**Comment by KimDahye** [comment]
https://github.com/KimDahye/NEXTStudentNetwork/wiki/API-%EB%AC%B8%EC%84%9C

**Comment by pjc0247** [comment]
깃허브 위키가, 가이드 쓰기에는 적절할 수 있는데 레퍼런스 쓰기에 많이 부적절합니다.
폴더별로 정리가 안되서요

따로 레포에 /docs 폴더 만드시고 거기에 서비스별로 api 정리해서 넣으시는게 깔끔할 것 같아요.

**Comment by KimDahye** [comment]
@pjc0247 오 그렇겠네~ 오키! :)

**Comment by KimDahye** [comment]
https://github.com/KimDahye/NEXTStudentNetwork/commit/f88084a31d76eaf3eefe7754bdc29f6562c95adb
