### ISSUE TITLE
body-parser 관련 오류 

### ISSUE THREAD

**Issue by honux77** [KimDahye/NEXTStudentNetwork#47]
시작시에 다음과 같은 경고가 발생하는데 안 나오면 좋겠지요? 

body-parser deprecated bodyParser: use individual json/urlencoded middlewares we
bapp\src\app.js:24:9
body-parser deprecated undefined extended: provide extended option node_modules\
body-parser\index.js:75:29

**Comment by KimDahye** [comment]
네~ 제가  body-parser 쓴다는 가정하에 코드 짠 게 있어서 body parser  추가할게요!

**Comment by KimDahye** [comment]
이미 추가하셨군요. pakage.json / app.js 파일 확인하였습니다~

**Comment by honux77** [comment]
ㅇㅇ 이게 버전과 사용법이 안 맞아서 난 건 같은데, 문서 확인하고 수정해야 할 것 같아.

**Comment by KimDahye** [comment]
넵~!

**Comment by honux77** [comment]
요렇게 해결.. 
app.use(bodyParser.urlencoded({extended: true}));
app.use(bodyParser.json());
