### ISSUE TITLE
admin일 경우 로그인 후 admin 페이지로 이동하게 하자 

### ISSUE THREAD

**Issue by honux77** [KimDahye/NEXTStudentNetwork#63]
그게 좋지 않을까요?

**Comment by KimDahye** [comment]
어드민 페이지를 갈 때 로그인 되어 있으면, 바로 보이는 거고 안되어 있으면 로그인 페이지로 리다이렉트 되는 거 아닌가요? 로그인 되어 있어도 한번 더 로그인해야하는 건가요?!

**Comment by honux77** [comment]
지금 어드민 유저가 로그인하면 profile 페이지로 가게 되는데, 어드민 유저는 굳이 profile 페이지로 갈 필요가 없는 것 같아서 말야. profile 페이지에 admin 페이지 링크가 있는 것도 아니라서 불편해.

**Comment by honux77** [comment]
그리고 남세한테 들은 건데 남세는 어드민 인증이 귀찮아서 어드민용 서버 웹앱을 따로 만들었대. 우리도 이렇게 했으면 더 쉬웠겠구나 싶더라.

**Comment by ghost** [comment]
보통 어드민은 정책상으로도 웹앱이랑 분리하는게 맞죠 ㅎㅎㅎ

**Comment by honux77** [comment]
@WooJaeWoo 그렇구나! 우리도 분리할까? ㅋㅋ

**Comment by honux77** [comment]
다른 포트에다 열면 될 것 같은데 ^^

**Comment by ghost** [comment]
분리하면 귀찮다는 엄청난 단점이 ㅋㅋㅋㅋㅋㅋ

**Comment by honux77** [comment]
그냥 인증할 때 어드민이면 인증하도록 코드 구현했어요.

**Comment by KimDahye** [comment]
처음에 질문을 잘못 이해했었군요~ 풀 리퀘스트 확인하면서 구현 확인할게요~

**Comment by honux77** [comment]
일단 큰 문제 없으므로 닫겠습니다.
